### ISSUE TITLE
Convert CSS code into SASS

### ISSUE THREAD

**Issue by milan090** [milan090/react-pomo-todos#1]
Currently we have one big App.css file in /src folder. Convert it into SASS. Install node-sass with npm to use sass files.

### (Optional)
Convert the new SASS file into individual SASS files that are related to each react component in respective folders.

**Comment by adeleke5140** [comment]
Hello. Could you assign this issue to me? I'm ready to take it up

**Comment by milan090** [comment]
> Hello. Could you assign this issue to me? I'm ready to take it up

Sure! Looking forward to your contributions :D

**Comment by adeleke5140** [comment]
I've got a question. I can't seem to find the link to the stylesheet

**Comment by milan090** [comment]
@adeleke5140 https://github.com/milan090/react-pomo-todos/blob/master/src/App.css

**Comment by adeleke5140** [comment]
I made a PR. What do you think?
